### ISSUE TITLE
How to automate mouse click in (x,y) coordinates using pyautoit?

### ISSUE THREAD

**Issue by balup34** [jacexh/pyautoit#10]
Using pyautoit, I am trying to click my mouse LEFT button, 2 times, in the (x=890 and y=574) coordinates. 

I have tried the below codes or options:

OPTIONS 1:

```
autoit.mouse_click(" 'left', 890, 574, 2")
    sleep(2)
```

OPTIONS 1:

```
autoit.mouse_click(" left, 890, 574, 2")
    sleep(2)
```

OPTIONS 1:

```
autoit.mouse_click(" $MOUSE_CLICK_LEFT, 890, 574, 2")
    sleep(2)
```

But no success.

How to do this, any idea?

**Comment by Aareon** [comment]
Is it only partially working or entirely broken? I notice an issue with your sleep command. It's gauged in milliseconds. Also, to use sleep, you must use 'autoit.sleep(param)'

Instead of "2", it should be "2000". Hope this helps. Keep me posted.

**Comment by balup34** [comment]
@Aareon Thanks for your answer. 

Now I have tried with below code:

		autoit.mouse_click("$MOUSE_CLICK_LEFT, 890, 574, 2")
		autoit.sleep(2000)

But  same issue. I mean its not clicking the LEFT button.

Could you please help me with the format that I am using here. is it correct "autoit.mouse_click("$MOUSE_CLICK_LEFT, 890, 574, 2") ".

Thanks in advance.

**Comment by balup34** [comment]
@Aareon . I found the working code.

Its works with : 
 
		autoit.mouse_click("",890, 574, 2)
		sleep(3)


NOTE : If I use autoit.sleep(2000), I am getting following error:

AttributeError: 'module' object has no attribute 'sleep'

**Comment by balup34** [comment]
I have referred following link "http://software-test-knowledge.blogspot.in/2014/01/automate-mouse-click-using-autoit.html". By default its choosing left button. That is why my code  autoit.mouse_click("",890, 574, 2) is working.

What if I want to press RIGHT mouse button here?

Please guide me how to send mouse key info in this code.

Thanks.

**Comment by balup34** [comment]
Got the answer for above question too... :)

autoit.mouse_click("left",890, 574, 2)

**Comment by Aareon** [comment]
Glad you found what you were looking for. Is there an explanation for why
2000ms didn't work, but 2 or 3 does?

**Comment by jacexh** [comment]
use `time.sleep(2)` instead of `autoit.sleep()`
I did not add `sleep` interface in `pyautoit`
