### ISSUE TITLE
Please fix installation problem and patch it into new realse.

### ISSUE THREAD

**Issue by jineshtest** [jacexh/pyautoit#16]
on 64-bit MAC system pyautoit can not installed. gives error below
sudo pip install pyautoit
The directory '/Users/jineshpatel/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/jineshpatel/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pyautoit
  Downloading PyAutoIt-0.4.zip (421kB)
    100% |████████████████████████████████| 430kB 2.0MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-91W3Mv/pyautoit/setup.py", line 9, in <module>
        import autoit
      File "autoit/__init__.py", line 6, in <module>
        from .autoit import options, properties, commands
      File "autoit/autoit.py", line 7, in <module>
        from ctypes.wintypes import *
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/wintypes.py", line 19, in <module>
        class VARIANT_BOOL(_SimpleCData):
    ValueError: _type_ 'v' not supported
    
Please fix and release new version

**Comment by Aareon** [comment]
Autoit is a Windows only language. Is there a reason you need to use it on
Mac?

**Comment by fenchu** [comment]
Bumped into this. I use Windows subsystem for linux (WSL) wont install there either.
