### ISSUE TITLE
Pyautoit Pixel Search

### ISSUE THREAD

**Issue by Lazy1997** [jacexh/pyautoit#20]
Pixel Search is not seem to work well with python.
[AutoItError: color is not found]
When i tested it with the notepad++ it work fine.
it is same script.

**Comment by ManaDork** [comment]
In autoit, the parameter order is (left, top, right, bottom). In PyAutoIt, the parameter order appears to be (right, top, left, bottom). 
Someone figured it out through experimentation. Apparently there are also some issues with performing the function on multiple monitors. This [page]( https://stackoverflow.com/questions/39921610/autoit-pixel-search-returning-color-is-not-found) has more info.
