### ISSUE TITLE
E  KeyError: 'PROGRAMFILES'

### ISSUE THREAD

**Issue by Vinodkumar545** [jacexh/pyautoit#22]
Hi,

I understand that pyautoit = 0.4, requires python 32-bit. So, accordingly I installed python 3.6.5 (32-bit) and create virtual environment to start working with the project. Pyautoit was installed and everything worked fine.

However, my project needs to be integrated with Jenkins, so I have started using tox. 

Upon using the tox, i'm facing an error only for this particular package pyauotoit. Could you please help us understand what does this error mean and what might be the suitable solution for this please?

Error messages
![tox](https://user-images.githubusercontent.com/34074855/42204290-e3ff9de8-7ebe-11e8-8ff0-6182ed4d5578.PNG)

tox.ini file
![tox_ini](https://user-images.githubusercontent.com/34074855/42204331-01203f36-7ebf-11e8-9ef8-d282220e8a09.PNG)

Vinodkumar

**Comment by JuxhinDB** [comment]
Hi Vinod, I don't follow this project much nor do I have experience with it. However for a workaround could you try running:

```
set PROGRAMFILES=foo
```

So that `if "(x86)" in os.environ['PROGRAMFILES']` returns `False`. I'm assuming that this _needs_ to be false because pyautoit needs to run on `x86` architecture.
