### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by dncarac** [jacexh/pyautoit#24]
Win 10
Py 3.7
Virtualenv

I cannot install the package.  I've tried pip from eclipse, pip from the command line, and downloading the source files and installing.  I've tried into a virtual environment and into the python installation directly.  All end with a 

OSError: [WinError 193] %1 is not a valid Win32 application

error.

Can you give me some pointers (or is there a double secret probation password).

Thanks,
Den

**Comment by evanliuyufeng** [comment]
if your windows version is 64 version, there is some error if you install directly. just follow the below instruction. 
first you need to download autoit zip file ,then unzip it. you need to change something in autoit.py
in line 15,change dll = "AutoItX3.dll" to dll = "AutoItX3_x64.dll", then use python setup.py install , you will succeed

**Comment by dncarac** [comment]
Thank you.
