### ISSUE TITLE
Does not detect the windows

### ISSUE THREAD

**Issue by Franjey** [jacexh/pyautoit#26]
![image](https://user-images.githubusercontent.com/11093607/51849735-153f8500-22ff-11e9-8759-06cba21077b0.png)

Upload windows after clicking "Upload Picture" in Instagram:

![image](https://user-images.githubusercontent.com/11093607/51849998-98f97180-22ff-11e9-90a4-3836ae40fa6d.png)

```
import autoit
from time import sleep

autoit.win_wait_active("Abrir", 5)
autoit.control_focus("Abrir", 1148)
sleep(2)
autoit.control_set_text("Abrir", 1148, "Text example")
```

`autoit.autoit.AutoItError: timeout on wait for activate window
`

Any idea? I am running the script while the window is open.

Edit:  I ran the same (ignoring the escape controls) code in SciTE editor (autoit scripting language) and works properly:
```
HotKeySet("^!x", "MyExit")
Local $Text = "C:\Users\Francisco\PycharmProjects\Instagram\Ipod_Touch.jpg"

; Script Start - Add your code below here
WinWaitActive("Abrir", "", 5)


; Set input focus to the edit control of Notepad using the handle returned by WinWait.
ControlFocus("Abrir", "", 1148)

; Wait for 2 seconds.
Sleep(2000)

; Send Text
ControlSetText("Abrir", "", 1148, $Text)

ControlClick("Abrir","", 1)

Func MyExit()
    Exit
EndFunc   ;==>MyExit
```

**Comment by Franjey** [comment]
Edit:  This is a full picture of the windows:

![image](https://user-images.githubusercontent.com/11093607/51849977-8e3edc80-22ff-11e9-8fd1-a98c37c39282.png)

**Comment by michealchew** [comment]
Hi,

Please try to change the following line:
autoit.win_wait_active("Abrir", 5) => autoit.win_activate("Abrir")

As win_wait_active is not activating your instagram upload photo directory browsing window automatically but it is waiting for it to be active. Use win_activate to force it to be active.

Yoong Loong
