### ISSUE TITLE
win_get_tittle 获取中文会出现乱码

### ISSUE THREAD

**Issue by YesHub** [jacexh/pyautoit#30]
全中文标题会出现乱码，不知道在哪里设置编码呢，英文字符开始的标题没问题。

**Comment by jacexh** [comment]
我目前手头并没有windows系统，印象中autoit也没提供编码设置接口。我估计是gbk与utf-8之间转码问题，建议多尝试下

**Comment by YesHub** [comment]
> 我目前是手头并没有Windows系统，印象中autoit也没提供编码设置接口。我估计是gbk与utf-8之间转码问题，建议多尝试下

谢谢回复，可以返回二进制吗，然后decode一下应该就不会有这些问题了
