### ISSUE TITLE
control_click() takes exactly 2 arguments

### ISSUE THREAD

**Issue by sn6uv** [jacexh/pyautoit#6]
Control click takes two arguments yet the docstring implies otherwise:

    In [2]: autoit.control_click?
    Type:        function
    String form: <function control_click at 0x031C40B0>
    File:        c:\python27\lib\site-packages\autoit\autoit.py
    Definition:  autoit.control_click(*args, **kwargs)
    Docstring:
    :param title:
    :param text:
    :param control:
    :param button:
    :param clicks:
    :param x:
    :param y:
    :return:

Came accross trying to right click on something.

**Comment by sn6uv** [comment]
I got this working using kwargs `button='right'`. This issue is invalid, but I guess some more documentaion/examples would be helpful since the interface is different to auto it [see autoit docs](https://www.autoitscript.com/autoit3/files/beta/autoit/docs/functions/ControlClick.htm).

**Comment by jacexh** [comment]
`pyautoit` is a wrapper of AutoItX.dll, the interfaces are a few different to AutoIt. You can get the AutoItX document in the installation folder of AutoIt.

**Comment by sn6uv** [comment]
Ah, I wasn't aware that AutoItX was different to AutoIt. Thanks!
