### ISSUE TITLE
no way to set/get environment variables

### ISSUE THREAD

**Issue by sn6uv** [jacexh/pyautoit#7]
The EnvSet and EnvGet methods are not implemented.

I tried to implement them, e.g.:

    @api.check(1, "set environment variable failed")
    def env_set(variable, value=None):
        """
    
        :param filename:
        :param work_dir:
        :param show_flag:
        :return:
        """
        if value is None:
            ret = AUTO_IT.AU3_EnvSet(LPCWSTR(variable))
        else:
            ret = AUTO_IT.AU3_EnvSet(LPCWSTR(variable), LPCWSTR(value))
        return ret

see  b2611d47a8, but it seems like they're not included in the DLL:

    AttributeError: function 'AU3_EnvSet' not found

Unsure on how to move forward with this.

**Comment by jacexh** [comment]
hi, 
`AU3_EnvSet` did not offered in `AutoItX3.dll`, you could call `os.environ` in python to instead of.

**Comment by sn6uv** [comment]
I see, I guess this is related to what you said in #6 (the differences between AutoIt and AutoItX). Thanks!
